[tool.poetry]
name = "cdm-tools"
version = "0.1.0"
description = ""
authors = ["lunelson-deloitte <lunelson@deloitte.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
